CREATE TABLE [dbo].[TMP_ProductInfo_old] (
    [Id]                          BIGINT          IDENTITY (1, 1) NOT NULL,
    [CategoryCode]                VARCHAR (10)    NULL,
    [SubCategoryCode]             INT             NULL,
    [SupplierCode]                VARCHAR (10)    NULL,
    [BrandCode]                   INT             NULL,
    [ItemCode]                    INT             NULL,
    [GlazersProductCode]          VARCHAR (50)    NULL,
    [SupplierName]                VARCHAR (500)   NULL,
    [BrandName]                   VARCHAR (500)   NULL,
    [ProductName]                 VARCHAR (500)   NULL,
    [AlternateName]               VARCHAR (500)   NULL,
    [SupplierLegalName]           VARCHAR (500)   NULL,
    [UPC_EAN_13]                  VARCHAR (50)    NULL,
    [SCC_14]                      VARCHAR (50)    NULL,
    [ABV_Per]                     DECIMAL (10, 2) NULL,
    [Category]                    VARCHAR (50)    NULL,
    [SubCategory]                 VARCHAR (500)   NULL,
    [ContainerType]               VARCHAR (50)    NULL,
    [Containers_Selling_Unit]     INT             NULL,
    [Selling_Units_Case]          INT             NULL,
    [Supplier_Internal_Code]      VARCHAR (50)    NULL,
    [Supplier_Internal_Code2]     VARCHAR (50)    NULL,
    [Supplier_Internal_Code3]     VARCHAR (50)    NULL,
    [Closure_Type]                VARCHAR (50)    NULL,
    [Closure_Weight]              DECIMAL (10, 2) NULL,
    [Bottle_Weight]               DECIMAL (10, 2) NULL,
    [Bottle_Height]               DECIMAL (10, 2) NULL,
    [Bottle_Length]               DECIMAL (10, 2) NULL,
    [Bottle_Width]                DECIMAL (10, 2) NULL,
    [Empty_Bottle_Weight]         DECIMAL (10, 2) NULL,
    [Lead_Time]                   INT             NULL,
    [Shipping_Term]               VARCHAR (50)    NULL,
    [Product_Designation]         VARCHAR (100)   NULL,
    [Origin_Country]              VARCHAR (100)   NULL,
    [Case_Height]                 DECIMAL (10, 2) NULL,
    [Case_Width]                  DECIMAL (10, 2) NULL,
    [Case_Length]                 DECIMAL (10, 2) NULL,
    [Case_Weight]                 DECIMAL (10, 2) NULL,
    [Cases_Per_Pallet]            INT             NULL,
    [Layers_Per_Pallet]           INT             NULL,
    [Cases_Per_Layer]             INT             NULL,
    [Cases_20ft_Container]        INT             NULL,
    [Cases_40ft_Container]        INT             NULL,
    [Cases_40ft_Heated_Container] INT             NULL,
    [Appellation]                 VARCHAR (50)    NULL,
    [Colour]                      VARCHAR (50)    NULL,
    [Residual_Sugar]              VARCHAR (50)    NULL,
    [Grape_Varietals]             DECIMAL (10, 2) NULL,
    [Variety]                     DECIMAL (10, 2) NULL,
    [Flavour]                     VARCHAR (50)    NULL,
    [HQ_Contact_Name]             VARCHAR (100)   NULL,
    [HQ_Contact_Name_Position]    VARCHAR (50)    NULL,
    [HQ_Address]                  NVARCHAR (1000) NULL,
    [HQ_City]                     VARCHAR (100)   NULL,
    [HQ_Postal_Code]              VARCHAR (50)    NULL,
    [HQ_Country]                  VARCHAR (100)   NULL,
    [HQ_Phone_Number]             VARCHAR (50)    NULL,
    [HQ_Email]                    NVARCHAR (256)  NULL,
    [ACD_British_Columbia]        BIGINT          NULL,
    [ACD_Alberta]                 BIGINT          NULL,
    [ACD_Saskatchewan]            BIGINT          NULL,
    [ACD_Manitoba]                BIGINT          NULL,
    [ACD_Ontario]                 BIGINT          NULL,
    [ACD_Quebec]                  BIGINT          NULL,
    [ACD_Newfoundland]            BIGINT          NULL,
    [ACD_New_Brunswick]           BIGINT          NULL,
    [ACD_Nova_Scotia]             BIGINT          NULL,
    [ACD_Prince_Edward_Island]    BIGINT          NULL,
    [ACD_Northwest_Territories]   BIGINT          NULL,
    [ACD_Nunavut]                 BIGINT          NULL,
    [ACD_Yukon]                   BIGINT          NULL,
    [CSPC_British_Columbia]       BIGINT          NULL,
    [CSPC_Alberta]                BIGINT          NULL,
    [CSPC_Saskatchewan]           BIGINT          NULL,
    [CSPC_Manitoba]               BIGINT          NULL,
    [CSPC_Ontario]                BIGINT          NULL,
    [CSPC_Quebec]                 BIGINT          NULL,
    [CSPC_Newfoundland]           BIGINT          NULL,
    [CSPC_New_Brunswick]          BIGINT          NULL,
    [CSPC_Nova_Scotia]            BIGINT          NULL,
    [CSPC_Prince_Edward_Island]   BIGINT          NULL,
    [CSPC_Northwest_Territories]  BIGINT          NULL,
    [CSPC_Nunavut]                BIGINT          NULL,
    [CSPC_Yukon]                  BIGINT          NULL,
    [CSPC_Quebec_Private_Order]   BIGINT          NULL,
    [ContainerVolume]             BIGINT          NULL,
    CONSTRAINT [PK_TMP_ProductInfo] PRIMARY KEY CLUSTERED ([Id] ASC)
);

